name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/note-birthday-bot:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/note-birthday-bot:latest

    - name: Deploy to server
      env:
        DOCKER_HOST: ${{ secrets.REMOTE_DOCKER_HOST }}
        DOCKER_CERT_PATH: ${{ secrets.REMOTE_DOCKER_CERT_PATH }}
        DOCKER_TLS_VERIFY: ${{ secrets.REMOTE_DOCKER_TLS_VERIFY }}
      run: |
        ssh -o StrictHostKeyChecking=no user@yourserver "docker pull ${{ secrets.DOCKER_USERNAME }}/note-birthday-bot:latest && docker-compose up -d"
